### ISSUE TITLE
Why there is a keystore file under source control?

### ISSUE THREAD

**Issue by safaorhan** [tasomaniac/WearPomodoro#4]
Link: https://github.com/pomopomo/WearPomodoro/blob/develop/distribution/debug.keystore

**Comment by tasomaniac** [comment]
It is a good practice to put debug keystore in your source control. That way all the people run the debug build will get the same certificate. If the app uses Google service, maps, Facebook SDK etc, it will just work for everyone.

**Comment by salimkayabasi** [comment]
As you can see this is a keystore for debug version. This idea for better if you are using more than one pc or lots of developer working on lots of devices.

No need to uninstall app from a shared device before developing
