### ISSUE TITLE
[Play store] "Not available in your country" -- why not?

### ISSUE THREAD

**Issue by AnotherKamila** [tasomaniac/WearPomodoro#6]
Hello,

I am not able to install your apps from the Play store (and since I am not an Android developer, I do not want to set up the build environment to build it myself). The Play store page says "This item is not available in your country". I am from Slovakia and currently based in Switzerland (not sure which country is taken into account). If this restriction is not intentional, could you please fix it?

Thanks a lot!

**Comment by tasomaniac** [comment]
Hello, thanks for the feedback. I am the developer of the app but I don't have access to the developer console anymore. Can you please send an email to info@vngrs.com
They should be able to change it.
